### ISSUE TITLE
1.7.10 Modded Server Crashes

### ISSUE THREAD

**Issue by HaniXP** [ForestryMC/ForestryMC#2123]
Crash Log = https://ghostbin.com/paste/7x4wn95b

Password : ender

I think it says something about Forestry or Gendustry.. Fueltimeburn or something idk.

What could be the cause of this? 

Solutions or any Answers is appreciated.

(Do not close the thread once i figure out the problem please :p)

**Comment by Nedelosk** [comment]
Duplicate of #1897
You are using the wrong version of thermos.

**Comment by HaniXP** [comment]
@Nedelosk but how come :o ? I am using the latest version of Thermos

**Comment by Nedelosk** [comment]
Absolutely no idea but #1897 and #1936 got fixed by updating Thermos.

**Comment by temp1011** [comment]
Is this the where the downloads are hosted? https://github.com/CyberdyneCC/Thermos. The latest version there is almost 2 years old. I guess it should be fine but it isn't being developed anymore..

**Comment by temp1011** [comment]
https://github.com/ForestryMC/ForestryMC/issues/1936 has `Thermos Version: cyberdynecc:Thermos:1.7.10-1614.58`. It didn't seem to work for them but maybe it will for you?

**Comment by MauveCloud** [comment]
I notice there are 5 commits since the latest release of Thermos.  I'm wondering if the people who fixed their issues by updating Thermos actually made custom builds to pick up those extra commits.  Issue 1936 was on build 58, which is apparently the latest official release, but the filer claims that updating fixed the issue.

**Comment by HaniXP** [comment]
I am not really sure updating to thermos built 58 will solve? some one has found out that i have an old version of modtweaker installed also and i need to update it , although i am using a modpack so this problem actually happened when i just updated forestry and gendustry to the latest 1.7.10 version.. 

---------------------------------
EDIT : Updated mod tweaker.. still the same error.

**Comment by HaniXP** [comment]
Fixed it.. 

After replacing forestry's latest 1.7.10 version with an outdated 1.3 version, The server strangely asked me that :- 

Missing Mods:
    Forestry : [4.1.0,)

which was really weird.. i then updated it back to 4.1.0 and everything is now solved.. no errors.

[ Also deleted useless addons like gendustry that doesnt support forestry's version more than 4.0, ]
